language: php
php: 
  - '5.5'
  - '5.6'
#  - '7.0'
#  - 'nightly'
env:
  global:
    - DBNAME='variation' 
    - DBUSER='deploy' 
    - DBPASS='variation'
services:
  - postgresql
addons:
  postgresql: 
  - "9.1"
  - "9.4"
install: 
  - composer install
  - ./scripts/install.sh
script: ./vendor/bin/phpunit src/
