language: php
php:
- '5.5'
- '5.6'
- '7.0'
- nightly
env:
  global:
  - DBNAME='variation'
  - DBUSER='deploy'
  - DBPASS='variation'
  - PGPORT='5432'
services:
- postgresql
addons:
  ssh_known_hosts: maya.elol.fr
  postgresql: '9.3'
before_install:
- openssl aes-256-cbc -K $encrypted_7194d2db567b_key -iv $encrypted_7194d2db567b_iv
  -in deploy/deploy_rsa.enc -out deploy/deploy_rsa -d
install:
- composer install
- ./scripts/install.sh
script: ./scripts/runtests.sh
before_deploy:
- pg_dump -U postgres -w $DBNAME | gzip > simmage.sql.gz
  && ls -l simmage.sql.gz
- eval "$(ssh-agent -s)"
- chmod 600 $TRAVIS_BUILD_DIR/deploy/deploy_rsa
- ssh-add $TRAVIS_BUILD_DIR/deploy/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: scp simmage.sql.gz "deploy@maya.elol.fr:" && ssh deploy@maya.elol.fr ./deploy-db.sh
  on:
    branch: master
    php: 5.6
